### ISSUE TITLE
Move away from the .io domain

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [iv-org/invidious.io#68]
>Internal discussion in the FreeTube room.
>
>Me to ﻿PrestonFT: i think its worth looking into this. 
>
> there are certain problems with .io zone space
> it "used to be cool" but a lot of people/companies have switched away from it
> http://www.thedarksideof.io/ and https://fortune.com/2020/08/31/crypto-fraud-io-domain-chagos-islands-uk-colonialism-cryptocurrency/ being a couple of reasons
>oh and also https://www.diagrams.net/blog/move-diagrams-net
>We wanted an ICANN controlled domain too

I wanted to make u guys aware of the issue because i noticed that u are using the .io domain too. We are now currently working on moving away from the domain because of these issues and maybe u want to do that too.

**Comment by TheFrenchGhosty** [comment]
It has already been discussed more than a year ago, we won't move.
