### ISSUE TITLE
All instances down

### ISSUE THREAD

**Issue by Abyssgrowth** [iv-org/invidious.io#71]
Hello,
since today 31.03.2023 it is impossible to view any youtube-channel on any of the instances listed on invidious.io
are you aware of the issue, is there an estimated time for when this get's fixed?

Error when attempting to view any channel page, for example this one: https://yewtu.be/channel/UCgFP46yVT-GG4o1TgXn-04Q

Could not extract JSON. Youtube API returned error 500 with message:
"ExecuteQuery for ChannelMiddlewareService-GetShelves failed: RET_CHECK failure (video/youtube/channels/frontend/shared/continuations/channel_middleware_token_encoding.cc:15) absl::WebSafeBase64Unescape(web_safe_token, &unescaped_token) ; OneMustSucceed: input 'mw_shelf_source_exp_continuation_unwrapper'; OneMustSucceed: input 'mw_shelf_source_exp_subgraphs'; OneMustSucceed: input 'mw_shelf_source_exp_empty_shelf_filter'; OneMustSucceed: input 'ShelfSourceExpansion__graph'; OneMustSucceed: input 'get_shelves_shelf_candidate_rank_sorter'; OneMustSucceed: input 'wrapped_main_subgraph'; OneMustSucceed: input 'pre_decoration_subgraph'; OneMustSucceed: input 'decoration_annotator_subgraph'; OneMustSucceed: input 'post_decoration_subgraph'; PropagateAllErrors: input 'GetShelvesEndpoint__graph'; PropagateAllErrors: input 'default_filter_survivor_probe_op'; PropagateAllErrors: input 'policy_enforcement_candidate_predicate'; /ChannelMiddlewareService.GetShelves RPC failed" 

PS: It is possible to view videos or browse "youtube" however, accessing channels doesn't work anymore.

**Comment by Cade66** [comment]
The culprit seems to be that [Youtube broke backwards compability, therefor all instanced no longer work](https://github.com/TeamPiped/Piped/issues/2487)
The issue affects Piped instances as well.

**Comment by DanielProg39** [comment]
Channels work properly on all instances again, so I think the issue should be closed

**Comment by Cade66** [comment]
Just tested a few YouTube videos redirected to Invidious and indeed they've now all displayed correctly.
FYI those same videos do not (yet) play on Piped ...
